---
- name: Check and start services
  hosts: all
  become: yes
  vars:
    manual_trigger: "{{ params.manual_trigger | default(false) }}"
  tasks:
    - name: Check if MySQL is running
      ansible.builtin.shell: "ps aux | grep mysql | grep -v grep"
      register: mysql_status
      ignore_errors: true

    - name: Start MySQL service if not running and job is not triggered manually
      ansible.builtin.shell: "nohup /home/knoldus/my.sh"
      when:
        - mysql_status.rc != 0
        - not manual_trigger

    - name: Force restart MySQL if job is triggered manually
      block:
        - name: Stop MySQL if running
          ansible.builtin.shell: "pgrep mysqld && nohup /home/knoldus/my_stop.sh"
          ignore_errors: true
        - name: Start MySQL
          ansible.builtin.shell: "nohup /home/knoldus/my.sh"
      when: manual_trigger
