---
- name: Check and start services
  hosts: all
  become: yes
  tasks:
    - name: Check and start services
      block:
        - name: Start MySQL service if not running
          ansible.builtin.shell: "nohup /home/knoldus/my.sh"

        - name: Start Grafana service if not running
          ansible.builtin.shell: "nohup /home/knoldus/gr.sh"
