---
- name: Check and start services
  hosts: all
  become: yes
  vars:
    manual_trigger: "{{ manual_trigger | default(false) }}"
  tasks:
    - name: Check if MySQL is running
      ansible.builtin.shell: "ps aux | grep mysql | grep -v grep"
      register: mysql_status
      ignore_errors: true

    - name: Start MySQL service if not running
      ansible.builtin.shell: "nohup /home/knoldus/my.sh"
      when: mysql_status.rc != 0

    - name: Check if Zookeeper is running
      ansible.builtin.shell: "ps aux | grep zookeeper | grep -v grep"
      register: zk_status
      ignore_errors: true

    - name: Start Zookeeper service if not running and job is not triggered manually
      ansible.builtin.shell: "nohup /home/knoldus/zk.sh"
      when:
        - zk_status.rc != 0
        - not manual_trigger

    - name: Force restart Zookeeper if job is triggered manually
      block:
        - name: Stop Zookeeper
          ansible.builtin.shell: "systemctl stop zookeeper"
        - name: Start Zookeeper
          ansible.builtin.shell: "systemctl start zookeeper"
      when: manual_trigger
