---
- name: Check and start services
  hosts: all
  become: yes
  vars:
    manual_trigger: "{{ manual_trigger | default(false) }}"
  tasks:
    - name: Check if MySQL is running
      ansible.builtin.shell: "ps aux | grep mysql | grep -v grep"
      register: mysql_status
      ignore_errors: true

    - name: Check if gr is running
      ansible.builtin.shell: "ps aux | grep grafana | grep -v grep"
      register: gr_status
      ignore_errors: true

    - name: Start mysql service if not running and job is not triggered manually
      ansible.builtin.shell: "nohup /home/knoldus/my.sh"
      when:
        - mysql_status.rc != 0
        - not manual_trigger

    - name: Force restart mysql if job is triggered manually
      block:
        - name: Stop mysql
          ansible.builtin.shell: "nohup /home/knoldus/my_stop.sh"
          ignore_errors: true
        - name: Start mysql
          ansible.builtin.shell: "nohup /home/knoldus/my.sh"
      when: manual_trigger
