---
- name: Check and start services
  hosts: all
  become: yes
  tasks:
    - name: Check and start services
      block:
        - name: Check if MySQL service is running
          ansible.builtin.shell: ps aux | grep "mysql" | grep -v grep
          register: mysql_service_status

        - name: Assert MySQL service is up
          ansible.builtin.assert:
            that:
              - mysql_service_status.rc == 0
            fail_msg: "MySQL service is down."
            success_msg: "MySQL service is up."

        - name: Check if Grafana service is running
          ansible.builtin.shell: ps aux | grep "grafana" | grep -v grep
          register: grafana_service_status

        - name: Assert Grafana service is up
          ansible.builtin.assert:
            that:
              - grafana_service_status.rc == 0
            fail_msg: "Grafana service is down."
            success_msg: "Grafana service is up."
