---
- name: Check and start services
  hosts: all
  become: yes
  tasks:
    - name: Check and start services
      block:        
        - name: Check if restart job is triggered automatically or manually
          ansible.builtin.command: "curl -s http://localhost:8080/job/manual_auto_job_testing/job/test/lastBuild/api/json"
          register: jenkins_job_info
        
        - name: Set fact if job is triggered automatically
          ansible.builtin.set_fact:
            triggered_automatically: "{{ jenkins_job_info.json.actions[?triggerCauses[*].shortDescription == 'Started by timer'].|length > 0 }}"
        
        - name: Check if MySQL is running
          ansible.builtin.shell: "ps aux | grep mysql | grep -v grep"
          register: mysql_status
          ignore_errors: true
        
        - name: Start MySQL service if not running
          ansible.builtin.shell: "nohup /home/knoldus/my.sh"
          when: mysql_status.rc != 0
        
        - name: Check if grafana is running
          ansible.builtin.shell: "ps aux | grep grafana | grep -v grep"
          register: gr_status
          ignore_errors: true
        
        - name: Start grafana service if not running and job is triggered automatically
          ansible.builtin.shell: "nohup /home/knoldus/gr.sh"
          when:
            - triggered_automatically
            - gr_status.rc != 0
        
        - name: Force restart Zookeeper if job is triggered manually
          ansible.builtin.shell: "nohup /home/knoldus/gr.sh restart"
          when: not triggered_automatically
