---
- name: Check and restart services
  block:
    - name: Check service status for mysql
      shell: ps aux | grep mysql | grep -v grep
      register: mysql_status
      ignore_errors: true
    
    - name: Start mysql if not running
      command: "nohup /home/knoldus/my.sh"
      when: mysql_status.rc = 0

